### ISSUE TITLE
Update to use latest jQuery libs

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/rosetta#12]
As the title says, update Rosetta to use the latest jQuery libs. Certainly not an easy task due to changes in the way css and underlying elements have changed. This also involves updating the javascript libs that depend on jQuery, and our custom tweaks to those libs.

**Comment by oxelson** [comment]
Unfortunately, this is not a simple fix.  The issue is jWizard plugin hasn't been updated in over three years and relies on jQuery code that is deprecated in newer versions ( > 1.8).

Options available to us:

1. A complete refactoring of the front-end to use something other than the jWizard plugin;
2. Contribute to the jWizard code (available on GitHub), so that it functions with the latest versions of jQuery; or
3. Fork the code and modify it for our own purposes.

I can contact the jWizard developer and see if there are any plans or interest on his behalf to continue development.  (Last code check-in was 2013, so I'm thinking probably not.)   If we consider #3 above, then we might as well share it with the original developer and opt for #2 instead.

I suggest an exploration of the alternatives (if there are any) and moving this issue to a later milestone.

**Comment by lesserwhirls** [comment]
This is stirring some memories of my attempt to upgrade jQuery to 1.11.1. At some point I was able to find a jWizard download that was updated to use jQuery >1.8 (I think I had to go to the authors personal site, maybe?). However, I was using the the full jQuery download, and not the custom download of jQuery, which threw in some wrenches when I started working with the CSS used in Rosetta. My work is on the jupdates branch:

https://github.com/Unidata/rosetta/tree/jupdates

The relevant commits start on November 13th:

https://github.com/Unidata/rosetta/commits/jupdates

I got lost in css hell when I switched from the custom jQuery libs to the full boat jQuery libs (the css was way different). Please excuse the tmp commits - I hadn't rebased to clean that stuff up at that point, as I was still trying to get things to work.

I know there is a jQuery migration tool, on the jQuery site, that says it will migrate >1.9 code to 3.x, so if we could get this working with 1.11.1, hopefully that would be an option.

**Comment by aleksandervines** [comment]
What is the status here? If one needs to refactor the front-end to use something other than jWizard, it seems like a good stage for getting it in, as parts of the logic needs to be reworked for #28

Also, I should note my comment about this that I had in a mail to support-rosetta@unidata.ucar.edu

```
Which "latest" version of jquery are you talking about? SlickGrid itself refers to the fork https://github.com/6pac/SlickGrid as to be "the most active atm". And it seems to be updated to jquery 1.11.3.

I see the need for an efficient grid-framework to display all the data, but do you really need to display the entire file? Usually just the header and a few more lines would be sufficient, I wouldn't think anyone would go through and look at all the data rows in the browser? Or perhaps slickgrid is used to more than just the display of data?

For jWizard, why not simply base it on jquery UI? It will be a bit more work to get the workflow in the ui going, but might be worth it to be based on an officially supported extension.
```

**Comment by lesserwhirls** [comment]
Complete re-write of the frontend addresses this.
