### ISSUE TITLE
Usage of template file

### ISSUE THREAD

**Issue by aleksandervines** [Unidata/rosetta#26]
I'm trying to understand how the template is supposed to work.

Why does the template-file, which is created with the netCDF file, only contain variable settings and not the same as the quicksave-one, which contains all settings?

The validateUploadedTemplateFile does not work as it's looking for a zip file. Should it instead test if the file extension is .template? Or have you some plan on working with zip files?

There are also a couple of other bugs in stepFunctions.uploadRosettaTemplate which I believe are related to copy-paste from uploadDataFile. I'm working on fixing these in https://github.com/nansencenter/rosetta/tree/master-av

**Comment by lesserwhirls** [comment]
Hi @aleksandervines,

The goal of the template is to be able to be directly used to create a netCDF file without going through the wizard interface. The idea was to be able to create one template file and apply it to multiple files in an automated fashion, rather than going through the wizard each time. Originally, the template file was an NcML file that was used to create a skeleton netCDF file. However, I decided to directly use the information in the session storage to do this rather than encoding that information into NcML. Because the NcML file only contained the information used to create the netCDF file, that's what the template contains. 

The "quick save" dumps the entire session storage such that a session can be completely restored at a later time for resuming work in the browser within the wizard interface.

When transforming multiple files, one way to do this would be to create a zip file containing the template, as well as all of the raw files that are needed to be converted. Since, at a minimum, you need a template file and one data file, I decided to have users upload a zip file containing those things as part of the workflow. I'll take a look at validateUploadedTemplateFile to see where it's being used. If it is used in both the wizard interface as well as the bulk file conversion workflow, then it should check for both .zip and .template.

Thanks for taking a look at this and providing fixes and feedback! It's greatly appreciated! On a side note, I'll be having surgery next week, but the end result is that I will be locked to my computer for several weeks following that, so I hope to be able to work more directly with your issues and get you up and running.

**Comment by aleksandervines** [comment]
So the quick save is intended for the "Upload, modify, and use an existing template" function, and the template generated with the netCDF for "Upload template and new data file, transform automatically"?

I'm still slightly confused by the use of two different template files and the terminology. As far as I can see, these two template files should contain the same data, as all information in the quicksave is needed for creating netCDF (at least for now).

Hope the surgery goes well and you can spend a lot of time in front of the computer in the near future :)

**Comment by aleksandervines** [comment]
Of course, the quick-save might not contain a finished template, as you may not have finished all the steps. Perhaps one should rename the quicksave to .quicksave if it's not complete, and call the "function" for "Upload, modify, and use an existing template or quicksave"?

**Comment by lesserwhirls** [comment]
So the intention is that both the quick-save and the finished template can be used by the "Upload, modify, and use an existing template". I agree that renaming the quick-save is a good idea to make things clear.

**Comment by aleksandervines** [comment]
I'd say this is more of a bug. The quick-save seems to work as intended, but the template contains _only_ the variable information.

How about removing the current template functionality, and just either
1. add a new button to download a "template" using the quick save function (and modify the filename),
2. or modify the quick save button on the "download converted file" tab?

I think option 1 would be best. See the fantastic visualization

![template_button](https://cloud.githubusercontent.com/assets/5492980/22826303/fbcad388-ef91-11e6-806c-6130b7852905.PNG)

**Comment by lesserwhirls** [comment]
The template has been completely redone, and is no longer tied to objects in session storage. The quick save feature isn't a part of the new interface, but will be implemented as part of user management.
